services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: store_rating
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
